export { default as Home} from './Home'
export { default as PageLogin} from './Login'
export { default as ContactDetail} from './ContactDetail'
export { default as About} from './About'
export { default as Favorites} from './Favorites'
export { default as AddUser} from './AddUser'